default_platform(:ios)

platform :ios do
  desc "Upload a new build to App Store Connect"
  lane :upload_build do
    api_key = app_store_connect_api_key(
      key_id: "T52YR38D64",
      issuer_id: "947c7ee7-4c99-4b7a-96b7-227a9bf35ed5",
      key_filepath: "/Users/banghuazhao/Development/secret/AppStore Connect API keys/AuthKey_T52YR38D64.p8",
      duration: 1200,
      in_house: false
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      ipa: "../build/ios/ipa/classic_reversi.ipa"
    )
  end
end
