default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    upload_to_play_store(
      track: 'production',
      rollout: '1.0',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end
end
